from pathlib import Path
import os
import re
import pandas as pd

BASE_DIR = Path(__file__).resolve().parent
DATASET_DIR = BASE_DIR / "datasets"

INPUT_WORKORDER_FILE = DATASET_DIR / "valid-WKO_and_component_times.csv"
INPUT_CLUSTERED_FILE = DATASET_DIR / "dataset.csv"
OUTPUT_FOLDER = BASE_DIR / "cluster_outputs"
OUTPUT_JOINED_FILE = DATASET_DIR / "final_joined_output.csv"


def clean_workorder_column(series: pd.Series) -> pd.Series:
    """
    Clean workorder identifiers for reliable joining.

    Purpose of the function in the overall pipeline:
    Workorder IDs may be read as numeric values with trailing '.0'. This
    function standardizes them into clean string identifiers so that records
    from the clustered dataset can be matched correctly with aggregated
    workorder metadata.

    Parameters:
    series (pd.Series): Series containing raw workorder identifiers.

    Returns:
    pd.Series: Cleaned workorder identifiers as stripped strings.
    """
    return series.astype(str).str.strip().str.replace(r"\.0$", "", regex=True)


def load_data(
    workorder_file: Path = INPUT_WORKORDER_FILE,
    clustered_file: Path = INPUT_CLUSTERED_FILE,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Load the workorder metadata file and clustered dataset file.

    Purpose of the function in the overall pipeline:
    This function reads the two input datasets required for the merge stage:
    the original workorder-level metadata and the clustered maintenance output
    produced by the semantic clustering pipeline.

    Parameters:
    workorder_file (Path): Path to the workorder metadata CSV file.
    clustered_file (Path): Path to the clustered dataset CSV file.

    Returns:
    tuple[pd.DataFrame, pd.DataFrame]: Loaded workorder metadata and clustered dataset.
    """
    df = pd.read_csv(workorder_file)
    dataset = pd.read_csv(clustered_file)
    return df, dataset


def build_joined_dataset(df: pd.DataFrame, dataset: pd.DataFrame) -> pd.DataFrame:
    """
    Aggregate workorder metadata and join it with clustered maintenance records.

    Purpose of the function in the overall pipeline:
    This function prepares the final merged dataset used for downstream
    analysis. It converts raw workorder metadata into one row per workorder,
    then joins that result with the clustered maintenance dataset generated by
    the clustering pipeline.

    Key design decisions:
    - Workorders are cleaned before joining to avoid format-based mismatches.
    - Dates are converted to datetime so that earliest open and latest close
      dates can be computed correctly.
    - Aggregation is done at the workorder level because multiple source rows
      can correspond to the same workorder.
    - An inner join is used so that only workorders present in both datasets
      appear in the final output.

    Assumptions or constraints:
    - The workorder metadata file contains the columns 'WKO#', 'Total_Time',
      'Date_Opened', 'Date_Closed', and 'Registration#'.
    - The clustered dataset contains 'WKO#' and clustering-related columns.

    Parameters:
    df (pd.DataFrame): Raw workorder metadata dataset.
    dataset (pd.DataFrame): Clustered maintenance dataset.

    Returns:
    pd.DataFrame: Final joined dataset with aggregated metadata and cluster labels.
    """
    df = df.copy()
    dataset = dataset.copy()

    # Standardize join keys in both datasets before any merge is attempted.
    df["WKO#"] = clean_workorder_column(df["WKO#"])
    dataset["WKO#"] = clean_workorder_column(dataset["WKO#"])

    # Datetime conversion is necessary so min/max aggregation reflects real chronology.
    df["Date_Opened"] = pd.to_datetime(df["Date_Opened"], errors="coerce")
    df["Date_Closed"] = pd.to_datetime(df["Date_Closed"], errors="coerce")

    # Columns not needed for the merged analytical dataset are removed early.
    df = df.drop(columns=["Part#", "TSO"], errors="ignore")

    # Multiple metadata rows may exist for a single workorder, so the data is
    # collapsed into one row per workorder before joining.
    agg_df = (
        df.groupby("WKO#", as_index=False)
        .agg(
            {
                "Total_Time": "sum",
                "Date_Opened": "min",
                "Date_Closed": "max",
                "Registration#": "first",
            }
        )
        .rename(
            columns={
                "WKO#": "workorder",
                "Total_Time": "total_time",
                "Date_Opened": "date_time_opened",
                "Date_Closed": "date_time_closed",
                "Registration#": "registration",
            }
        )
    )

    dataset = dataset.rename(columns={"WKO#": "workorder"})

    # Clean the renamed join columns to ensure key consistency after renaming.
    agg_df["workorder"] = agg_df["workorder"].astype(str).str.strip()
    dataset["workorder"] = dataset["workorder"].astype(str).str.strip()

    # Overlap statistics help verify how much of the metadata can be linked to
    # clustered records and diagnose missing workorders in either dataset.
    agg_wko = set(agg_df["workorder"])
    dataset_wko = set(dataset["workorder"])

    print("Unique workorders in agg_df:", len(agg_wko))
    print("Unique workorders in dataset:", len(dataset_wko))
    print("Matching unique workorders:", len(agg_wko & dataset_wko))
    print("Only in agg_df:", len(agg_wko - dataset_wko))
    print("Only in dataset:", len(dataset_wko - agg_wko))

    # Inner join keeps only the workorders that exist in both datasets.
    final_df = pd.merge(agg_df, dataset, on="workorder", how="inner")

    final_df = final_df.rename(
        columns={
            "ATA_Code": "ata_code",
            "PROBLEM": "problem",
            "DATE": "date",
            "ACTION": "action",
        }
    )

    # Restrict the output to the columns needed for the final analytical dataset.
    final_df = final_df[
        [
            "workorder",
            "date_time_opened",
            "date_time_closed",
            "registration",
            "total_time",
            "ata_code",
            "problem",
            "date",
            "action",
            "cluster",
            "cluster_name",
        ]
    ]

    print("df shape:", df.shape)
    print("dataset shape:", dataset.shape)
    print("agg_df shape:", agg_df.shape)
    print("final_df shape:", final_df.shape)

    return final_df


def save_cluster_csvs(
    final_df: pd.DataFrame,
    output_folder: Path = OUTPUT_FOLDER,
) -> None:
    """
    Save one CSV file per cluster from the joined dataset.

    Purpose of the function in the overall pipeline:
    This function creates cluster-specific outputs so that records belonging to
    each cluster can be inspected independently after the merge stage.

    Key design decisions:
    - File names are sanitized to avoid invalid filesystem characters.
    - The output directory is created automatically if it does not exist.

    Parameters:
    final_df (pd.DataFrame): Final joined dataset.
    output_folder (Path): Directory where cluster-wise CSV files will be saved.

    Returns:
    None: This function writes cluster-specific CSV files to disk.
    """
    os.makedirs(output_folder, exist_ok=True)

    for cluster_name, group in final_df.groupby("cluster"):
        # Cluster names may contain characters unsuitable for file names.
        safe_name = re.sub(r"[^\w]+", "_", str(cluster_name))
        file_name = output_folder / f"cluster_{safe_name}.csv"
        group.to_csv(file_name, index=False)
        print(f"{cluster_name}: {len(group)} rows saved to {file_name}")

    print("Cluster-wise CSV files generated successfully.")


def save_full_output(
    final_df: pd.DataFrame,
    output_file: Path = OUTPUT_JOINED_FILE,
) -> None:
    """
    Save the complete joined dataset to disk.

    Purpose of the function in the overall pipeline:
    This function writes the full merged output that combines workorder
    metadata with cluster assignments.

    Parameters:
    final_df (pd.DataFrame): Final joined dataset.
    output_file (Path): Path where the full joined CSV should be saved.

    Returns:
    None: This function writes the complete joined dataset to disk.
    """
    os.makedirs(output_file.parent, exist_ok=True)
    final_df.to_csv(output_file, index=False)
    print(f"Full joined output saved to {output_file}")


def main() -> None:
    """
    Execute the complete dataset merge workflow.

    Purpose of the function in the overall pipeline:
    This function orchestrates the merge stage by loading inputs, building the
    joined dataset, saving the full merged output, and exporting cluster-wise
    CSV files.

    Parameters:
    None: This function does not accept external parameters.

    Returns:
    None: This function runs the merge workflow and writes outputs to disk.
    """
    os.makedirs(DATASET_DIR, exist_ok=True)

    df, dataset = load_data()
    final_df = build_joined_dataset(df, dataset)

    save_full_output(final_df)
    save_cluster_csvs(final_df)


if __name__ == "__main__":
    main()
